In [ ]:
!pip install opencv-python-headless
!pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
def extract_hmp(video):
  print(video)
  # Define the parameters for the HMP feature extraction
  win_size = (32, 32)
  block_size = (16, 16)
  block_stride = (8, 8)
  cell_size = (8, 8)
  nbins = 15  # use 15 bins per channel for a total of 15*15*15=6075 bins

  # Load the video and initialize the HOG descriptor
  video_path = '/content/gdrive/MyDrive/Videos/'+video
  video_cap = cv2.VideoCapture(video_path)
  hog = cv2.HOGDescriptor(win_size, block_size, block_stride, cell_size, nbins)

  # Define the batch size and initialize the feature array
  batch_size = 50  # process 50 frames at a time
  features = []

  # Process the video in batches
  while video_cap.isOpened():
      # Read the next batch of frames from the video
      frames = []
      for i in range(batch_size):
          ret, frame = video_cap.read()
          if not ret:
              break
          frame = cv2.resize(frame, win_size)
          frames.append(frame)
      if not frames:
          break
      
      # Compute HMP features for the batch of frames
      batch_features = []
      for frame in frames:
          gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
          descriptors = hog.compute(gray)
          batch_features.append(descriptors)
      
      # Append the batch features to the feature array
      batch_features = np.stack(batch_features, axis=0)
      features.append(batch_features)

  # Concatenate the feature batches into a single array
  features = np.concatenate(features, axis=0)

  # Save the features to disk
  # output_file = '/path/to/features.npy'
  # np.save(output_file, features)
  print(features)
  print(len(features[0]))

  with open(r'/content/gdrive/MyDrive/HMP/'+video, 'w') as fp:
      for item in features:
          item = abs(item)
          # write each item on a new line
          fp.write("%s " % item)
      print('Done')
for i in range(12):
  
  extract_hmp(f'nS-NuGbrDK4_part_{i}.mp4')

nS-NuGbrDK4_part_0.mp4
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.09859905 0.01396118 0.00633241 ... 0.06437678 0.13860191 0.10654815]
 [0.08007667 0.04733083 0.0126765  ... 0.05148138 0.11697192 0.15970853]
 [0.072487   0.03084865 0.0126341  ... 0.11224397 0.15759501 0.11686429]]
540
Done
nS-NuGbrDK4_part_1.mp4
[[0.07710699 0.03642007 0.00641803 ... 0.08735766 0.15155114 0.12836681]
 [0.09750341 0.02383367 0.00770683 ... 0.08493038 0.11853161 0.17620018]
 [0.10114413 0.03804013 0.00799933 ... 0.09940027 0.07311238 0.13420966]
 ...
 [0.32862988 0.0364345  0.0114535  ... 0.05409679 0.06162229 0.14303261]
 [0.32454467 0.05883115 0.01642489 ... 0.03048511 0.03818497 0.20186003]
 [0.32312298 0.04358948 0.01147246 ... 0.02432581 0.02654992 0.24368857]]
540
Done
nS-NuGbrDK4_part_2.mp4
[[0.2988868  0.02151092 0